# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chargerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chargerApp
  pod 'Alamofire'

  target 'chargerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chargerAppUITests' do
    # Pods for testing
  end

end
